# VK Teams Bot Configuration Example

# Bot token from VK Teams Bot API
bot-token: "your-bot-token-here"

# API URL (optional, uses default if not specified)
api-url: "https://example.com/bot/v1"

# Webhook configuration (optional)
webhook-url: "https://your-domain.com/webhook"
webhook-port: 8080

# Logging configuration
log-level: info # debug, info, warn, error

# HTTP timeout in milliseconds
timeout-ms: 30000
# Database configuration (future feature)
# database:
#   host: localhost
#   port: 5432
#   name: vkteams_bot
#   user: postgres
#   password: password

# AI/LLM configuration (future feature)
# ai:
#   provider: openai  # openai, ollama
#   api-key: "your-api-key"
#   model: "gpt-4"
#   temperature: 0.7
